# Generated by Django 3.2.4 on 2021-08-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, null=True)),
                ('course_code', models.CharField(max_length=50)),
                ('syllabus', models.CharField(max_length=200)),
                ('course_trainer', models.CharField(max_length=50)),
                ('course_schedule', models.FileField(upload_to='')),
                ('course_duration', models.CharField(max_length=30)),
            ],
        ),
    ]
