# Generated by Django 3.2.4 on 2021-08-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('number_of_lessons_taought', models.PositiveSmallIntegerField()),
                ('profile', models.ImageField(blank=True, upload_to='uploads')),
                ('age', models.PositiveSmallIntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=50)),
                ('contract', models.CharField(max_length=30)),
                ('date_hired', models.DateField(max_length=20)),
                ('languages', models.CharField(choices=[('E', 'English'), ('S', 'Swahili'), ('K', 'Kikuyu'), ('R', 'kinyarwanda'), ('U', 'Kiganda')], max_length=2)),
            ],
        ),
    ]
