# Generated by Django 3.2.4 on 2021-08-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='languages',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='number_of_lessons_taought',
            new_name='number_of_lessons_taught',
        ),
    ]
