# Generated by Django 3.2.4 on 2021-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210812_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
