# Generated by Django 3.2.4 on 2021-09-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_student_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email_Adress',
            new_name='email_adress',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
